FROM golang:1.12 as build-stage

RUN set -x && \
    mkdir /build

WORKDIR /build

LABEL vendor=ONHO\ Incorporated \
      onho.io.is-prod="" \
      onho.io.version="0.0.1-beta" \
      onho.io.release-date="2020-01-01"

ENV CGO_ENABLED=0

RUN git clone https://github.com/kuritka/onho.io . && \
    go mod init github.com/kuritka/onho.io && \
    go list -e $(go list -f . -m all) && \
    go build -o main . && \
    groupadd -g 1001 onhouser && \
    useradd -r -u 1001 -g onhouser onhouser

#-----------------------------------------------------
FROM scratch as release-stage

WORKDIR /app

COPY --from=build-stage /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build-stage /build/services/frontend/static /app/static
COPY --from=build-stage /build/services/frontend/templates /app/templates
COPY --from=build-stage /build/main /app/main
COPY --from=build-stage /etc/passwd /etc/passwd

USER onhouser

ENTRYPOINT ["./main"]
