version: v1
kind: Deployment
metadata:
  name: frontend
  namespace: onho-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
    template:
      metadata:
        labels:
          app: frontend
      spec:
        containers:
        - name: frontend
          image: acronhosbx.azurecr.io/frontend:0.3
          ports:
          - containerPort: 8080
#
#+ ports
#+ environment variables

