---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: frontend-gateway
  namespace: onho-dev
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
        privateKey: /etc/istio/ingressgateway-certs/tls.key
      hosts:
        - "onho.cz"
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "onho.cz"
      tls:
        httpsRedirect: true
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend
  namespace: onho-dev
spec:
  hosts:
    - "onho.cz"
  gateways:
    - frontend-gateway
  http:
    - match:
        - uri:
            prefix: /
        - uri:
            prefix: /health
      route:
        - destination:
            port:
              number: 8081
            host: frontend
      maxAge: "86400s"