---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: frontend-ingress
spec:
  rules:
    - host: onho.cz
      http:
        paths:
          - path: /
            backend:
              serviceName: frontend
              servicePort: 5000
