apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sendbox
  name: secretfiles-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secretfiles-volume
      version: v1
  template:
    metadata:
      labels:
        app: secretfiles-volume
        version: v1
    spec:
      volumes:
        - name: auth
          secret:
            secretName: auth.key
      containers:
        - name: backend
          image: acronhosbx.azurecr.io/onho:0.23
          args: [backend]
          ports:
            - containerPort: 8080
          env:
            -  name: ONHO_CLIENT_PORT
               value: "8080"
            -  name: ONHO_ENVIRONMENT
               value: "dev"
#kubectl create secret generic auth -n sendbox --from-file=./auth.key --from-file=./auth.key.pub
# file can be read by program from /etc/auth/auth.key
#another way is to make key as base64 and put it directly to secret file and pass it as environment variable
          volumeMounts:
            - name: auth
              mountPath: /etc/auth/
              readOnly: true